USE [projectLS]
GO

/****** Object:  Table [dbo].[Race]    Script Date: 2/28/2023 6:24:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Race](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RaceName] [varchar](20) NOT NULL,
	[PetTypeId] [int] NOT NULL,
 CONSTRAINT [PK_Race] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Race]  WITH CHECK ADD  CONSTRAINT [FK_Race_PetType] FOREIGN KEY([PetTypeId])
REFERENCES [dbo].[PetType] ([Id])
GO

ALTER TABLE [dbo].[Race] CHECK CONSTRAINT [FK_Race_PetType]
GO


