USE [projectLS]
GO

/****** Object:  Table [dbo].[PetType]    Script Date: 2/28/2023 6:23:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PetType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PetTypeName] [varchar](20) NOT NULL,
	[DefaultPetPic] [varchar](max) NULL,
 CONSTRAINT [PK_PetType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


